name: Update-Packages-Github

on:
  schedule:
  - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set Global Variables
      run: |
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
        echo "PACKAGES_DIR=$GITHUB_WORKSPACE\packages" >> $GITHUB_ENV
      shell: bash

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (Chocolatey)
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Write-Host "Chocolatey is not installed. Installing now..."
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Error "Failed to install Chocolatey. Aborting."
            exit 1
          }
        }
      shell: pwsh

    - name: Update and Push Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Update packages
        . "${{ env.SCRIPTS_DIR }}\auto-package-updates.ps1"
        try {
          $updatedPackages = (Get-Updates -PackagesDir "${{ env.PACKAGES_DIR }}")
        } catch {
          Write-Host "An error occurred while getting updates: $_"
          exit 1
        }
    
        # Push packages to GitHub Packages if there are updates
        if ($updatedPackages.Count -gt 0) {
          foreach ($packagePath in $updatedPackages) {
            if (Test-Path $packagePath) {
              Write-Host "Pushing package: $packagePath"
              dotnet nuget push "$packagePath" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
            } else {
              Write-Host "Package path $packagePath not found."
            }
          }
        } else {
          Write-Host "No updated packages to push."
        }
      shell: pwsh
    

    - name: Commit and Push to GitHub
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add icons/ 
        git add packages/*.nupkg
        # Commit the updated packages and list of updated packages in the commit message
        git commit -m "Automatically Updated: ${{ env.UPDATED_PACKAGES}}" || echo "No changes to commit"
        git push origin ${{ github.ref }}
      shell: pwsh
