name: Check-For-Updates-Github

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check For Updates
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
