name: Update-Packages-Github

on:
  schedule:
  - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set Global Variables
      run: |
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
        echo "PACKAGES_DIR=$GITHUB_WORKSPACE\packages" >> $GITHUB_ENV
      shell: bash

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (Chocolatey)
      run: |
        $logFile = "$Env:GITHUB_WORKSPACE\logs\update-log.txt"
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Write-Host "Chocolatey is not installed. Installing now..."
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Host "Chocolatey failed to install. Exiting..."
            # log that chocolatey failed to install
            "Chocolatey failed to install." | Out-File -Append -FilePath $logFile
            exit 1
          }
        }
      shell: pwsh

    - name: Update and Push Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $logFile = "$Env:GITHUB_WORKSPACE\logs\update-log.txt"
        . "${{ env.SCRIPTS_DIR }}\auto-package-updates.ps1"
        try {
          $updatedPackages = (Get-Updates -PackagesDir "${{ env.PACKAGES_DIR }}")
          if ($updatedPackages.Count -gt 0) {
            foreach ($packagePath in $updatedPackages) {
              if (Test-Path $packagePath) {
                try {
                  dotnet nuget push "$packagePath" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
                  "Successfully updated $packagePath" | Out-File -Append -FilePath $logFile
                } catch {
                  "Failed to push package: $packagePath" | Out-File -Append -FilePath $logFile
                }
              } else {
                "Package path $packagePath not found." | Out-File -Append -FilePath $logFile
              }
            }
          } else {
            "No updated packages to push." | Out-File -Append -FilePath $logFile
          }
        } catch {
          "An error occurred while getting updates: $_" | Out-File -Append -FilePath $logFile
        }
      shell: pwsh

    - name: Commit and Push to GitHub
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add $Env:GITHUB_WORKSPACE\logs\update-log.txt
        git add icons/ 
        git add packages/*.nupkg
        git commit -m "Update packages and log" -a || echo "No changes to commit"
        git push origin ${{ github.ref }}
      shell: pwsh
