name: CreatePackage

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for Chocolatey
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Write-Host "Chocolatey is not installed. Installing now..."
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          
          # Verify installation
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Error "Failed to install Chocolatey. Aborting."
            exit 1
          }
        }
      shell: pwsh

    - name: Validate Directory Structure and Files
      run: |
        if (!(Test-Path -Path "./scripts/fetch-latest-release.ps1")) {
          Write-Error "Required PowerShell script does not exist."
          exit 1
        }
      shell: pwsh

    - name: Create packages directory if not exists
      run: |
        if (-not (Test-Path -Path "./packages/")) {
          New-Item -Path "./packages/" -ItemType Directory
        }
      shell: pwsh
      
    - name: Execute PowerShell Script
      run: .\scripts\fetch-latest-release.ps1
      shell: pwsh

    - name: List files in scripts directory
      run: |
        Get-ChildItem -Path "./scripts/"
      shell: pwsh
    
    - name: Move .nupkg files to packages directory
      run: |
        Move-Item -Path "./scripts/*.nupkg" -Destination "./packages/"
      shell: pwsh
    
    - name: List files in packages directory
      run: |
        Get-ChildItem -Path "./packages/"
      shell: pwsh

    - name: Commit and Push .nupkg File
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./packages/*.nupkg
        git commit -m "Add new Chocolatey package"
        git push https://${{ secrets.GIT_PAT }}@github.com/YourUsername/YourRepo.git
      shell: pwsh
    


