name: CreatePackage - Modular

on:
  workflow_dispatch:
    inputs:
      repoUrl:
        description: 'GitHub Repository URL or Direct Asset Download URL'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set Global Variables
      run: |
        echo "REPO_URL=${{ github.event.inputs.repoUrl }}" >> $GITHUB_ENV
        echo "ROOT_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
      shell: bash

    - name: Checkout Code
      uses: actions/checkout@v2    

    - name: Install Dependencies (Chocolatey)
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
      shell: pwsh

    - name: Create Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . "${{ env.SCRIPTS_DIR}}\create-package-github.ps1"
        Initialize-GithubPackage -InputUrl "${{ env.REPO_URL}}"
      shell: pwsh

    - name: Commit and Push to GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add icons/ pachakges/
        git commit -m "Automated Package Creation: ${{ env.REPO_URL}}" || echo "No changes to commit"
        git push origin ${{ github.ref }}
      shell: pwsh
