name: Create-Packages-Github

on:
  workflow_dispatch:
    inputs:
      repoUrls:
        description: 'List of GitHub Repository URLs or Direct Asset Download URLs separated by commas, spaces, or new lines'
        required: true

jobs:
  pre_process:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Generate Matrix
      id: set-matrix
      run: |
        matrix=$(echo -n '['; echo "${{ github.event.inputs.repoUrls }}" | tr ', ' '\n' | tr ',' '\n' | tr ' ' '\n' | sed '/^$/d' | sort -u | awk -vORS=',' '{ print "\""$0"\""}' | sed 's/,$//'; echo -n ']')
        echo "matrix=${matrix}" >> $GITHUB_OUTPUT  # Updated according to new guidelines  
  build:
    runs-on: windows-latest
    needs: pre_process
    strategy:
      fail-fast: false
      matrix:
        repoUrl: ${{fromJson(needs.pre_process.outputs.matrix)}}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create and Checkout to Unique Local Branch
      run: |
        unique_branch="staging_$(echo "${{ matrix.repoUrl }}" | sed 's/[~^: /@*?]//g')"
        git checkout -b $unique_branch || exit 1
      shell: bash

    - name: Set Global Variables
      run: |
        echo "REPO_URL=${{ matrix.repoUrl }}" >> $GITHUB_ENV
        echo "ROOT_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
      shell: bash

    - name: Install Chocolatey
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) || exit 1
        }
      shell: pwsh

    - name: Create Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . "${{ env.SCRIPTS_DIR}}\create-package-github.ps1" || exit 1
        Initialize-GithubPackage -InputUrl "${{ env.REPO_URL}}" || exit 1
      shell: pwsh

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
  
        unique_branch="staging_$(echo "${{ matrix.repoUrl }}" | sed 's/[~^: /@*?]//g')"

        # Identify existing pull requests for the branch
        existing_prs=$(gh pr list --state open --head "$unique_branch")
        echo "Listing all open PRs for the branch:"
        echo "Existing PRs: $existing_prs"


        # If an existing pull request is found, close it
        if [[ ! -z "$existing_prs" ]]; then
          pr_number=$(echo "$existing_prs" | awk '{print $1}')
          echo "Closing PR #$pr_number"
          gh pr close "$pr_number" --comment "Closing PR as a new PR has been created for the same branch."
          echo "Closed PR #$pr_number"
        fi

        # Commit and push changes
        echo "Committing and pushing changes to branch $unique_branch"
        git add . || exit 1
        git commit -m "Automatically Created: ${{ matrix.repoUrl }}" || echo "No changes to commit"
        echo "Pushing changes to branch $unique_branch"
        git push --set-upstream origin $unique_branch --force || exit 1
        echo "Pushed changes to branch $unique_branch"
        
        # Create the PR
        echo "Creating PR for branch $unique_branch"
        pr_output=$(gh pr create --title "Automated PR: $unique_branch" --body "This PR was automatically created by github-actions[bot]" --base ${{ github.event.repository.default_branch }} --head $unique_branch --label "auto gh-package" --fill)
        echo "Created PR: $pr_output"
      shell: bash

  post_process:
    needs: build  # Make sure to depend on the build job to get its outputs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto-Merge Created PRs using gh pr merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
  
          git fetch --all
          git branch -a
  
          # Debug: List all open PRs
          echo "Listing all open PRs:"
          gh pr list --state open
  
          # Fetch PR numbers for specific label
          pr_list_label=$(gh pr list --state open --label "auto gh-package")
          # Convert to array
          echo "Listing all PRs matching the label (auto gh-package):"
          pr_array_label=($pr_list_label)
          for pr in "${pr_array_label[@]}"; do
            gh pr view $pr
          done
          

          # Fetch PR numbers for author
          pr_list_author=$(gh pr list --state open --author "github-actions")
          # Convert to array
          echo "Listing all PRs created by github-actions:"
          pr_array_author=($pr_list_author)
          for pr in "${pr_array_author[@]}"; do
            gh pr view $pr
          done

          # Fetch PR numbers for author
          pr_list_author2=$(gh pr list --state open --author "github-actions[bot]")
          # Convert to array
          echo "Listing all PRs created by github-actions[bot]:"
          pr_array_author2=($pr_list_author2)
          for pr in "${pr_array_author2[@]}"; do
            gh pr view $pr
          done

          # List all found PRs matching label
          echo "Listing all PRs matching both the label and author:"
          pr_array=()
          for pr in "${pr_array_label[@]}"; do
            if [[ " ${pr_array_author[@]} " =~ " ${pr} " ]]; then
              pr_array+=($pr)
              gh pr view $pr
            fi
          done
  
          # Loop through PR numbers and attempt to merge each
          for pr in "${pr_array[@]}"; do
            gh pr merge $pr --merge --auto || echo "Failed to merge PR #$pr"
          done
  
        shell: bash