name: Create-Package-Github

on:
  workflow_dispatch:
    inputs:
      repoUrls:
        description: 'List of GitHub Repository URLs or Direct Asset Download URLs separated by commas, spaces, or new lines'
        required: true

env:
  CHOCO_INSTALL_PATH: C:\ProgramData\chocolatey

jobs:
  pre_process:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Generate Matrix
      id: set-matrix
      run: |
        urls=$(echo "${{ github.event.inputs.repoUrls }}" | tr -d '\n' | tr ',' '\n' | tr ' ' '\n' | awk '{$1=$1};1' | sort -u)
        echo "matrix=${urls[@]}" >> $GITHUB_ENV
      shell: bash

  build:
    runs-on: windows-latest
    needs: pre_process
    strategy:
      fail-fast: false
      matrix:
        repoUrl: ${{fromJson(needs.pre_process.outputs.matrix)}}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache Chocolatey Install
      uses: actions/cache@v2
      with:
        path: ${{ env.CHOCO_INSTALL_PATH }}
        key: ${{ runner.os }}-choco-install-${{ hashFiles('**/*.ps1') }}
        restore-keys: ${{ runner.os }}-choco-install-

    - name: Set Global Variables
      run: |
        echo "REPO_URL=${{ matrix.repoUrl }}" >> $GITHUB_ENV
        echo "ROOT_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
      shell: bash

    - name: Install Dependencies (Chocolatey)
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
      shell: pwsh

    - name: Create Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . "${{ env.SCRIPTS_DIR }}\create-package-github.ps1"
        Initialize-GithubPackage -InputUrl "${{ env.REPO_URL }}"
      shell: pwsh

    - name: Stage Changes for Commit
      run: |
        echo "${{ matrix.repoUrl }}" >> $GITHUB_WORKSPACE/success.txt
        git add packages/${{ matrix.repoUrl }}/
        git commit -m "Staging for ${{ matrix.repoUrl }}" || (echo "${{ matrix.repoUrl }}" >> $GITHUB_WORKSPACE/failure.txt; exit 0)
      shell: pwsh

    - name: Upload success and failure lists
      uses: actions/upload-artifact@v2
      with:
        name: result-files
        path: |
          ${{ github.workspace }}/success.txt
          ${{ github.workspace }}/failure.txt

  post_process:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download success and failure lists
      uses: actions/download-artifact@v2
      with:
        name: result-files

    - name: Set Git Identity
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Merge Staged Changes and Generate Commit Message
      run: |
        git pull --no-commit
        successes=$(cat success.txt)
        commit_msg="Successfully created packages for: $successes"
        git commit -m "$commit_msg"
        git push origin ${{ github.ref }}
      shell: bash

    - name: Failure Notification
      run: |
        failures=$(cat failure.txt)
        echo "Jobs failed for the following repositories: $failures"
      shell: bash
