name: Create-Package-Github

on:
  workflow_dispatch:
    inputs:
      repoUrls:
        description: 'List of GitHub Repository URLs or Direct Asset Download URLs separated by commas, spaces, or new lines'
        required: true

jobs:
  pre_process:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Generate Matrix
      id: set-matrix
      run: |
        urls=$(echo "${{ github.event.inputs.repoUrls }}" | tr -d '\n' | tr ',' '\n' | tr ' ' '\n' | awk '{$1=$1};1' | sort -u)
        matrix_list="[\"$(echo "$urls" | tr '\n' '","' | sed 's/,$//')\"]"
        echo "matrix_list=$matrix_list"
        echo "matrix=$matrix_list" | tee -a $GITHUB_ENV
        echo "::set-output name=matrix::$matrix_list"
      shell: bash

  build:
    runs-on: windows-latest
    needs: pre_process
    strategy:
      fail-fast: false
      matrix:
        repoUrl: ${{ needs.pre_process.outputs.matrix }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Initialize Result Files
      run: |
        echo "" > success.txt
        echo "" > failure.txt
      shell: pwsh

    - name: Set Global Variables
      run: |
        echo "REPO_URL=${{ matrix.repoUrl }}" >> $GITHUB_ENV
        echo "ROOT_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "SCRIPTS_DIR=$GITHUB_WORKSPACE\scripts" >> $GITHUB_ENV
      shell: bash

    - name: Install Chocolatey
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
      shell: pwsh

    - name: Create Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . "${{ env.SCRIPTS_DIR}}\create-package-github.ps1"
        Initialize-GithubPackage -InputUrl "${{ env.REPO_URL}}"
      shell: pwsh

    - name: Upload success and failure lists
      uses: actions/upload-artifact@v3
      with:
        name: result-files
        path: |
          success.txt
          failure.txt

  post_process:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Download success and failure lists
      uses: actions/download-artifact@v3
      with:
        name: result-files

    - name: Commit and Push to GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add icons/ packages/
        git commit -m "Automated Package Creation: ${{ env.REPO_URL }}" || echo "No changes to commit"
        git push origin ${{ github.ref }}
      shell: bash
